"""
PharmaSense Agent — Reasoning Pipeline: Steps 4 & 5
======================================================
Step 4: Synthesis            (build the structured, cited brief)
Step 5: Safety & Compliance  (strip diagnostic/prescriptive language,
                               attach disclaimer, force human review)

DESIGN NOTE ON STEP 4:
Synthesis is template-based by default — every sentence is generated
from structured data + KB citations using deterministic templates.
This guarantees:
  - The demo NEVER fails due to a missing/expired API key
  - Every claim is traceable to a data field or KB entry (no hallucination
    risk by construction)
  - Reviewers can audit the exact template logic

An OPTIONAL LLM rewrite pass can be enabled by setting the
PHARMASENSE_LLM_REWRITE=1 environment variable + OPENAI_API_KEY. If
enabled, the LLM is given the already-cited bullet points and asked
ONLY to improve phrasing — it is explicitly instructed not to add new
claims or remove citations. If the LLM call fails for any reason, the
pipeline silently falls back to the template output. This makes the
LLM an enhancement, never a dependency.
"""

import os
import re
from typing import List, Dict, Any

from app.models import (
    Patient, DetectedSignal, RetrievedEvidence, KBEntry,
    Brief, BriefSection,
)


DISCLAIMER = (
    "This brief was generated by an AI reasoning agent (PharmaSense Agent) "
    "based on SYNTHETIC data for demonstration purposes. It does not "
    "constitute a diagnosis, prescription, or treatment recommendation. "
    "All findings require review by a qualified care team before any "
    "clinical decision is made."
)

# Phrases that must never appear in agent output. If the (optional) LLM
# rewrite pass introduces any of these, the step 5 safety check strips
# the offending sentence entirely and logs it.
PROHIBITED_PATTERNS = [
    r"\bdiagnos\w*\b",
    r"\bprescri\w*\b",
    r"\bshould (start|stop|switch|take|begin|discontinue)\b",
    r"\bwe recommend (starting|stopping|switching)\b",
    r"\bis suffering from\b",
    r"\bhas (a |an )?(condition|disease)\b",
]


# ---------------------------------------------------------------------------
# STEP 4 — Synthesis
# ---------------------------------------------------------------------------

def step4_synthesize_brief(
    patient: Patient,
    normalized: Dict[str, Any],
    signals: List[DetectedSignal],
    evidence: List[RetrievedEvidence],
    kb_entries: List[KBEntry],
) -> Brief:
    concepts = normalized["ontology_concepts"]

    # --- Summary section ---
    if not signals:
        summary = (
            f"Patient {patient.patient_id}'s treatment journey shows no significant "
            f"pattern-based risk signals based on the rules currently applied by "
            f"PharmaSense Agent. [data]"
        )
    else:
        severities = [s.severity for s in signals]
        high_count = severities.count("high")
        summary = (
            f"Patient {patient.patient_id}'s treatment journey shows "
            f"{len(signals)} pattern-based signal(s) "
            f"({high_count} high severity), summarized below with supporting "
            f"evidence from the curated knowledge base. [data]"
        )

    # --- Detected signals section ---
    signal_bullets = []
    evidence_by_signal = {e.signal_id: e for e in evidence}
    for signal in signals:
        citation_ids = []
        ev = evidence_by_signal.get(signal.signal_id)
        if ev and ev.kb_matches:
            citation_ids = [m["kb_id"] for m in ev.kb_matches]

        citation_str = ", ".join(f"[{cid}]" for cid in citation_ids) if citation_ids else "[no KB match]"
        bullet = f"({signal.severity.upper()}) {signal.description} {citation_str}"
        signal_bullets.append(bullet)

    if not signal_bullets:
        signal_bullets = ["No risk signals were detected by the current rule set. [data]"]

    # --- Supporting evidence section ---
    evidence_bullets = []
    seen_kb_ids = set()
    for ev in evidence:
        for match in ev.kb_matches:
            if match["kb_id"] in seen_kb_ids:
                continue
            seen_kb_ids.add(match["kb_id"])
            entry = next((k for k in kb_entries if k.kb_id == match["kb_id"]), None)
            if entry:
                evidence_bullets.append(
                    f"{entry.title} (relevance {match['relevance_score']}): "
                    f"{entry.summary} [{entry.kb_id}]"
                )

    if not evidence_bullets:
        evidence_bullets = ["No knowledge base entries were retrieved for this patient's signals."]

    # --- Discussion points section ---
    discussion_bullets = _generate_discussion_points(signals, concepts)

    brief = Brief(
        patient_id=patient.patient_id,
        summary=summary,
        sections=[
            BriefSection(heading="Detected Signals", bullets=signal_bullets),
            BriefSection(heading="Supporting Evidence", bullets=evidence_bullets),
            BriefSection(heading="Suggested Discussion Points for Care Team", bullets=discussion_bullets),
        ],
        requires_human_review=True,
        disclaimer=DISCLAIMER,
    )

    # Optional LLM rewrite pass (phrasing only, never adds claims)
    if os.environ.get("PHARMASENSE_LLM_REWRITE") == "1":
        brief = _try_llm_rewrite(brief)

    return brief


def _generate_discussion_points(signals: List[DetectedSignal], concepts: Dict[str, Any]) -> List[str]:
    if not signals:
        return ["Continue routine monitoring per standard cadence. [data]"]

    points = []
    signal_ids = {s.signal_id for s in signals}

    if "SIG-RAPID-SWITCH" in signal_ids:
        points.append(
            "Review whether each prior line of therapy was given an adequate "
            "trial period before the switch was made. [SIG-RAPID-SWITCH]"
        )
    if "SIG-THERAPY-GAP" in signal_ids:
        points.append(
            "Confirm continuity of care during the identified therapy gap and "
            "assess any impact on metabolic control. [SIG-THERAPY-GAP]"
        )
    if "SIG-BIOMARKER-REBOUND" in signal_ids:
        points.append(
            "Consider an adherence-focused conversation before evaluating "
            "further therapy changes, given the rebound pattern. [SIG-BIOMARKER-REBOUND]"
        )
    if "SIG-ADHERENCE-DECLINE" in signal_ids:
        points.append(
            "Explore adherence barriers (cost, side effects, lifestyle) that may "
            "have contributed to the recent decline. [SIG-ADHERENCE-DECLINE]"
        )
    if "SIG-PLATEAU-LOW-ADHERENCE" in signal_ids:
        points.append(
            "Evaluate whether the current 'stable' trend reflects a plateau "
            "rather than adequate control, given current adherence levels. [SIG-PLATEAU-LOW-ADHERENCE]"
        )
    if "SIG-LONG-SINGLE-LOT" in signal_ids:
        points.append(
            "Consider a periodic re-assessment of the current therapy given the "
            "absence of any documented LOT switch. [SIG-LONG-SINGLE-LOT]"
        )
    if "SIG-BIOMARKER-WORSENING" in signal_ids:
        points.append(
            "Prioritize review of this patient given the consistent worsening "
            "trend in biomarker levels. [SIG-BIOMARKER-WORSENING]"
        )

    if len(signals) >= 2:
        points.append(
            "Multiple concurrent signals were detected — consider a consolidated "
            "review rather than addressing each in isolation. [KB-010]"
        )

    return points


def _try_llm_rewrite(brief: Brief) -> Brief:
    """
    Optional enhancement: ask an LLM to improve phrasing of the bullets
    WITHOUT adding new claims or removing citations. Falls back silently
    to the original brief on any error (missing key, network, etc).
    """
    try:
        from openai import OpenAI
        client = OpenAI()  # reads OPENAI_API_KEY from env

        for section in brief.sections:
            rewritten_bullets = []
            for bullet in section.bullets:
                prompt = (
                    "Rewrite the following clinical-style note for clarity and "
                    "professional tone. Do NOT add any new facts, numbers, or claims. "
                    "Do NOT remove or alter any bracketed citation tags like [KB-001] "
                    "or [SIG-...] or [data] — keep them exactly as-is at the end of "
                    "the sentence. Do NOT use the words 'diagnose', 'prescribe', or "
                    "give any instruction to start/stop/switch medication.\n\n"
                    f"Text: {bullet}\n\nRewritten:"
                )
                resp = client.chat.completions.create(
                    model="gpt-4o-mini",
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0.2,
                    max_tokens=150,
                )
                rewritten_bullets.append(resp.choices[0].message.content.strip())
            section.bullets = rewritten_bullets

        return brief
    except Exception:
        # Any failure -> silently keep the template-based brief
        return brief


# ---------------------------------------------------------------------------
# STEP 5 — Safety & Compliance Check
# ---------------------------------------------------------------------------

def step5_safety_check(brief: Brief) -> Dict[str, Any]:
    """
    Scans every bullet/sentence in the brief for prohibited diagnostic or
    prescriptive language. Any matching sentence is stripped and logged
    in the audit trail returned alongside the (possibly modified) brief.

    Always forces requires_human_review = True and ensures the disclaimer
    is present, regardless of upstream behavior.
    """
    audit_log: List[Dict[str, str]] = []

    for section in brief.sections:
        cleaned_bullets = []
        for bullet in section.bullets:
            violation = _find_prohibited_language(bullet)
            if violation:
                audit_log.append({
                    "section": section.heading,
                    "original_text": bullet,
                    "violation_pattern": violation,
                    "action": "stripped",
                })
                # Replace with a safe placeholder rather than silently dropping,
                # so the audit trail is fully visible in the UI.
                cleaned_bullets.append(
                    "[Content removed by safety layer — contained "
                    "diagnostic/prescriptive language not permitted in agent output.]"
                )
            else:
                cleaned_bullets.append(bullet)
        section.bullets = cleaned_bullets

    # Force safety invariants
    brief.requires_human_review = True
    if DISCLAIMER not in brief.disclaimer:
        brief.disclaimer = DISCLAIMER

    return {
        "checked_sections": len(brief.sections),
        "violations_found": len(audit_log),
        "audit_log": audit_log,
        "requires_human_review": True,
        "disclaimer_present": True,
    }


def _find_prohibited_language(text: str) -> str | None:
    lowered = text.lower()
    for pattern in PROHIBITED_PATTERNS:
        if re.search(pattern, lowered):
            return pattern
    return None
